### ISSUE TITLE
Plx fix with new hud exe my lord

### ISSUE THREAD

**Issue by anhlatuan91** [Stridemann/PoeHUD_FullRareSetManager#1]
i got this bug, using win10 64 bit
http://imgur.com/a/rs3PO

**Comment by Stridemann** [comment]
You should update poehud to last version.

**Comment by anhlatuan91** [comment]
i update hud to the lastest version, then this happened.

**Comment by Stridemann** [comment]
U should update also this plugin too. I just test it, works fine for me.

**Comment by anhlatuan91** [comment]
restart pc and it work hmm . . .
