### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by NoNick96** [Stridemann/PoeHUD_FullRareSetManager#18]
`D:\NoNick\afdsgs\PoeHelper\Plugins\Source\FullRareSetManager\FullRareSetManagerCore.cs(33,30) : error CS0115: 'FullRareSetManagerCore.ReceiveEvent(string, object)': no suitable method found to override
`

**Comment by NoNick96** [comment]
I've tried to clone it into PoeHelper\Plugins\Source\FullRareSetManager and use CompilePlugins.bat.
ExileApi v.0.3.1-alpha.

**Comment by gitzet** [comment]
Can't make it to work either, can someone please try to compile it and upload it somewhere already compiled?

Edit: I've just realized it can be even used as uncompiled and it works, but it does have bug with daggers, for some reason they are in red square as ignored items.

**Comment by NoNick96** [comment]
I've managed to compile it with current source version (as of writing this comment) of ExileApi.
