### ISSUE TITLE
Plugin 3.1 ready?

### ISSUE THREAD

**Issue by anonaut** [Stridemann/PoeHUD_FullRareSetManager#4]
Hey Stridemann,

first thanks for your work - the video looks incredible.

secondly, does this plugin work with current poehud version? i got the following error:
"Error in plugin constructor! Plugin: Core, Error: Exception has been thrown by the target of invocation."

I saw your commit 2 hours ago so i'm not sure if the error is on my side or if you have to change some things to get it working again for 3.1

regards
Mako

**Comment by nymann** [comment]
Update to the newest version of PoeHud 🌞

**Comment by anonaut** [comment]
Works 👍
